//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O2Micro.BCLabManager.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O2Micro.BCLabManager.Shell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All batteries.
        /// </summary>
        internal static string AllBatteriesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllBatteriesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All battery types.
        /// </summary>
        internal static string AllBatteryTypesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllBatteryTypesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All executors.
        /// </summary>
        internal static string AllExecutorsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllExecutorsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All requests.
        /// </summary>
        internal static string AllRequestsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllRequestsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New battery type.
        /// </summary>
        internal static string BatteryTypeViewModel_DisplayName {
            get {
                return ResourceManager.GetString("BatteryTypeViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New battery.
        /// </summary>
        internal static string BatteryViewModel_DisplayName {
            get {
                return ResourceManager.GetString("BatteryViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash Board.
        /// </summary>
        internal static string DashBoardViewModel_DisplayName {
            get {
                return ResourceManager.GetString("DashBoardViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon.
        /// </summary>
        internal static string ExecutorViewModel_Command_Abandon {
            get {
                return ResourceManager.GetString("ExecutorViewModel_Command_Abandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Assets.
        /// </summary>
        internal static string ExecutorViewModel_Command_AssignAssets {
            get {
                return ResourceManager.GetString("ExecutorViewModel_Command_AssignAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string ExecutorViewModel_Command_Commit {
            get {
                return ResourceManager.GetString("ExecutorViewModel_Command_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string ExecutorViewModel_Command_Execute {
            get {
                return ResourceManager.GetString("ExecutorViewModel_Command_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidate.
        /// </summary>
        internal static string ExecutorViewModel_Command_Invalidate {
            get {
                return ResourceManager.GetString("ExecutorViewModel_Command_Invalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new battery.
        /// </summary>
        internal static string MainWindowViewModel_Command_CreateNewBattery {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new battery type.
        /// </summary>
        internal static string MainWindowViewModel_Command_CreateNewBatteryType {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewBatteryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new request.
        /// </summary>
        internal static string MainWindowViewModel_Command_CreateNewRequest {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all batteries.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllBatteries {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllBatteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all battery types.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllBatteryTypes {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllBatteryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all executors.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllExecutors {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllExecutors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all requests.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllRequests {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Dash Board.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewDashBoard {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC Lab Manager.
        /// </summary>
        internal static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request.
        /// </summary>
        internal static string RequestViewModel_DisplayName {
            get {
                return ResourceManager.GetString("RequestViewModel_DisplayName", resourceCulture);
            }
        }
    }
}
