//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCLabManager.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCLabManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All batteries 的本地化字符串。
        /// </summary>
        internal static string AllBatteriesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllBatteriesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All battery types 的本地化字符串。
        /// </summary>
        internal static string AllBatteryTypesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllBatteryTypesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All executors 的本地化字符串。
        /// </summary>
        internal static string AllExecutorsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllExecutorsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All requests 的本地化字符串。
        /// </summary>
        internal static string AllRequestsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllRequestsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New battery type 的本地化字符串。
        /// </summary>
        internal static string BatteryTypeViewModel_DisplayName {
            get {
                return ResourceManager.GetString("BatteryTypeViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New battery 的本地化字符串。
        /// </summary>
        internal static string BatteryViewModel_DisplayName {
            get {
                return ResourceManager.GetString("BatteryViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dash Board 的本地化字符串。
        /// </summary>
        internal static string DashBoardViewModel_DisplayName {
            get {
                return ResourceManager.GetString("DashBoardViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abandon 的本地化字符串。
        /// </summary>
        internal static string ExecutorViewModel_Command_Abandon {
            get {
                return ResourceManager.GetString("ExecutorViewModel_Command_Abandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign Assets 的本地化字符串。
        /// </summary>
        internal static string ExecutorViewModel_Command_AssignAssets {
            get {
                return ResourceManager.GetString("ExecutorViewModel_Command_AssignAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commit 的本地化字符串。
        /// </summary>
        internal static string ExecutorViewModel_Command_Commit {
            get {
                return ResourceManager.GetString("ExecutorViewModel_Command_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute 的本地化字符串。
        /// </summary>
        internal static string ExecutorViewModel_Command_Execute {
            get {
                return ResourceManager.GetString("ExecutorViewModel_Command_Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalidate 的本地化字符串。
        /// </summary>
        internal static string ExecutorViewModel_Command_Invalidate {
            get {
                return ResourceManager.GetString("ExecutorViewModel_Command_Invalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new battery 的本地化字符串。
        /// </summary>
        internal static string MainWindowViewModel_Command_CreateNewBattery {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new battery type 的本地化字符串。
        /// </summary>
        internal static string MainWindowViewModel_Command_CreateNewBatteryType {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewBatteryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new request 的本地化字符串。
        /// </summary>
        internal static string MainWindowViewModel_Command_CreateNewRequest {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CreateNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View all batteries 的本地化字符串。
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllBatteries {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllBatteries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View all battery types 的本地化字符串。
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllBatteryTypes {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllBatteryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View all executors 的本地化字符串。
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllExecutors {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllExecutors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View all requests 的本地化字符串。
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllRequests {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Dash Board 的本地化字符串。
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewDashBoard {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BC Lab Manager 的本地化字符串。
        /// </summary>
        internal static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New request 的本地化字符串。
        /// </summary>
        internal static string RequestViewModel_DisplayName {
            get {
                return ResourceManager.GetString("RequestViewModel_DisplayName", resourceCulture);
            }
        }
    }
}
